version: '3'

services:

  #-----------------------#
  #         MySQL         #
  #-----------------------#

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: Jm9Ca9Sh6

  #-----------------------#
  #     Crawler Python    #
  #-----------------------#

  crawler:
    image: python:3.8-alpine
    container_name: py-crawler
    working_dir: /usr/app/crawler/
    restart: on-failure
    command: sh -c "pip install pyyaml requests schedule mysql-connector-python deep_translator vaderSentiment && python3 -B ./"
    environment:
      DUMP_PATH: /usr/app/crawler/dump.yml
      TWITTER_BEARER: AAAAAAAAAAAAAAAAAAAAAOPAlgEAAAAAY8QaIwGnXCJuPPGPo3NqSJc4apc%3DzU73mVa5pD1MtNr6WhBZkBHsYs8VjkPFwHwhxdSlL2Q5kCVUIU
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PSW: Jm9Ca9Sh6
      MYSQL_DB: politics_stats
    depends_on:
      - mysql
    volumes:
      - $PWD/py-crawler/:/usr/app/crawler/

  #-----------------------#
  #        NodeJS         #
  #-----------------------#

  node-ui:
    image: node:19-alpine3.16
    container_name: node-ui
    restart: unless-stopped
    working_dir: /home/app/node-ui/
    command: sh -c "npm install && node app.js"
    volumes:
      - $PWD/node-ui:/home/app/node-ui/
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PSW: Jm9Ca9Sh6
      MYSQL_DB: politics_stats
    
      
volumes:
  mysql-data: