version: '3'

services:

  #-----------------------#
  #  MySQL Politics Data  #
  #-----------------------#

  mysql-politics:
    image: mysql:8.0
    container_name: mysql-politics
    restart: "no"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql-politics-data:/var/lib/mysql
      - ./mysql-db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: Jm9Ca9Sh6

  #-----------------------#
  #   Grafana for Charts  #
  #-----------------------#

  grafana-charts:
    image: grafana/grafana:8.2.6
    container_name: grafana-charts
    user: "0:0"
    ports:
      - 3000:3000
    depends_on:
      - mysql-politics
    volumes:
      - grafana-data:/var/lib/grafana
      - $PWD/grafana-charts/:/etc/grafana/
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2
        delay: 5s

  #-----------------------#
  #     Crawler Python    #
  #-----------------------#

  py-crawler:
    image: python:3.8-alpine
    container_name: py-crawler
    working_dir: /home/app/crawler/
    restart: "no"
    command: sh -c "pip install pyyaml requests schedule mysql-connector-python deep_translator vaderSentiment && python3 -B ./"
    volumes:
      - $PWD/py-crawler/:/home/app/crawler/
    depends_on:
      - mysql-politics
    environment:
      DUMP_PATH: /home/app/crawler/dump.yml
      TWITTER_BEARER: AAAAAAAAAAAAAAAAAAAAAOPAlgEAAAAAY8QaIwGnXCJuPPGPo3NqSJc4apc%3DzU73mVa5pD1MtNr6WhBZkBHsYs8VjkPFwHwhxdSlL2Q5kCVUIU
      MYSQL_HOST: mysql-politics
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PSW: Jm9Ca9Sh6
      MYSQL_DB: politics_stats    

  #-----------------------#
  #        NodeJS         #
  #-----------------------#

  node-ui:
    image: node:19-alpine3.16
    container_name: node-ui
    restart: "no"
    working_dir: /home/app/node-ui/
    command: sh -c "npm install && node app.js"
    volumes:
      - $PWD/node-ui:/home/app/node-ui/
    ports:
      - 8080:8080
    depends_on:
      - mysql-politics
      - grafana-charts
    environment:
      MYSQL_HOST: mysql-politics
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PSW: Jm9Ca9Sh6
      MYSQL_DB: politics_stats

  #-----------------------#
  # Python Health Checker #
  #-----------------------#
    
  py-health:
    image: python:3.8-alpine
    container_name: py-health
    working_dir: /home/app/health/
    restart: unless-stopped
    command: sh -c "pip install pyyaml requests slack-sdk && python3 -B ./"
    volumes:
      - $PWD/py-health/:/home/app/health/
    depends_on:
      - mysql-politics
      - py-crawler
      - node-ui
    environment:
      IS_RELEASE: 0
      SERVERLIST_PATH: /home/app/health/settings.yml
      CHECK_TIME_SECONDS: 1
      TELEGRAM_TOKEN: '6012596464:AAE5Zg423LgO5dAQdqUTWd834qu9xoIttYA'

volumes:
  mysql-politics-data:
  grafana-data: