{
 "title": "Politics Stats",
 "time": { "from": "now-10d", "to": "now-1d" },
 "templating": {
  "list": [
   { "name": "group_name" },
   { "name": "account_name" }
  ]
 },
 "panels": [
  {
   "title": "General Compare",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Tweet Length Compare",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  name AS metric,\n  avg_len\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date)\nORDER BY date"
      }
     ]
    },
    {
     "title": "Number of Analysed Tweets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  name AS metric,\n  fetched_tweets_count\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date)\nORDER BY date"
      }
     ]
    },
    {
     "title": "Number of Followers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  name AS metric,\n  followers_count\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date)\nORDER BY date"
      }
     ]
    },
    {
     "title": "Average Retweets Compare",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  name AS metric,\n  avg_retweets\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date)\nORDER BY date"
      }
     ]
    },
    {
     "title": "Average Likes Compare",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  name AS metric,\n  avg_likes\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date)\nORDER BY date"
      }
     ]
    },
    {
     "title": "Average Replies Compare",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  name AS metric,\n  avg_replies\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date)\nORDER BY date"
      }
     ]
    }
   ]
  },
  {
   "title": "Group's Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Followers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  followers_count\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date) AND\n  name = '$group_name'\nORDER BY date"
      }
     ]
    },
    {
     "title": "Number of Analysed Tweets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  fetched_tweets_count\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date) AND\n  name = '$group_name'\nORDER BY date"
      }
     ]
    },
    {
     "title": "Average Tweet Length History",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  avg_len\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date) AND\n  name = '$group_name'\nORDER BY date"
      }
     ]
    },
    {
     "title": "Average Likes History",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  avg_likes\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date) AND\n  name = '$group_name'\nORDER BY date"
      }
     ]
    },
    {
     "title": "Average Retweets History",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  avg_retweets\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date) AND\n  name = '$group_name'\nORDER BY date"
      }
     ]
    },
    {
     "title": "Average Replies History",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  avg_replies\nFROM twitter_dailystats_group\nWHERE\n  $__timeFilter(date) AND\n  name = '$group_name'\nORDER BY date"
      }
     ]
    }
   ]
  },
  {
   "title": "Account's Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Followers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  followers_count\nFROM twitter_dailystats_accounts\nWHERE\n  $__timeFilter(date) AND\n  handle = '$account_name'\nORDER BY date"
      }
     ]
    },
    {
     "title": "Number of Analysed Tweets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  fetched_tweets_count\nFROM twitter_dailystats_accounts\nWHERE\n  $__timeFilter(date) AND\n  handle = '$account_name'\nORDER BY date"
      }
     ]
    },
    {
     "title": "Average Tweet Length History",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  avg_len\nFROM twitter_dailystats_accounts\nWHERE\n  $__timeFilter(date) AND\n  handle = '$account_name'\nORDER BY date"
      }
     ]
    },
    {
     "title": "Average Likes History",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  avg_likes\nFROM twitter_dailystats_accounts\nWHERE\n  $__timeFilter(date) AND\n  handle = '$account_name'\nORDER BY date"
      }
     ]
    },
    {
     "title": "Average Retweets History",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  avg_retweets\nFROM twitter_dailystats_accounts\nWHERE\n  $__timeFilter(date) AND\n  handle = '$account_name'\nORDER BY date"
      }
     ]
    },
    {
     "title": "Average Replies History",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  avg_replies\nFROM twitter_dailystats_accounts\nWHERE\n  $__timeFilter(date) AND\n  handle = '$account_name'\nORDER BY date"
      }
     ]
    }
   ]
  }
 ]
}