apiVersion: 1

datasources:
  - name: Politics-Data
    type: mysql
    url: mysql-politics:3306
    user: root
    database: politics_stats
    orgId: 1
    version: 1
    editable: true
    secureJsonData:
      password: Jm9Ca9Sh6
    jsonData:
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
