version: '3'

servers:
  - server:
      address: py-crawler
      contact: '@as_politics_stats_health_checker'
      contact_type: telegram
  - server:
      address: mysql-politics
      contact: '@as_politics_stats_health_checker'
      contact_type: telegram
  - server:
      address: node-ui
      contact: '@as_politics_stats_health_checker'
      contact_type: telegram
  - server:
      address: grafana-charts
      contact: '@as_politics_stats_health_checker'
      contact_type: telegram
  - server:
      address: py-crawler
      contact: T01BEMLB81Y/B04UHEQMRG8/Luf9890JtZpdajYfcioxBzea
      contact_type: slack
  - server:
      address: mysql-politics
      contact: T01BEMLB81Y/B04UHEQMRG8/Luf9890JtZpdajYfcioxBzea
      contact_type: slack
  - server:
      address: node-ui
      contact: T01BEMLB81Y/B04UHEQMRG8/Luf9890JtZpdajYfcioxBzea
      contact_type: slack
  - server:
      address: grafana-charts
      contact: T01BEMLB81Y/B04UHEQMRG8/Luf9890JtZpdajYfcioxBzea
      contact_type: slack